config/routes.rb
Rails.application.routes.draw do
  mount AcmePlugin::Engine, at: '/'

  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  root 'pages#home'
  get :faq, to: 'pages#faq'

  get :about, to: 'pages#about'
  get :caution, to: 'pages#caution'
  get :map, to: 'pages#map'
  get :schedule, to: 'pages#schedule'
  get :application, to: 'pages#application'
  get 'sites/:area_code', to: 'pages#site', as: :site

  get :group, to: 'pages#group'

  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'

  get 'dreams/value', to: 'dreams#value'
  get 'dreams/interview', to: 'dreams#interview'
  get 'dreams/data', to: 'dreams#data'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'

  delete :likes, to: 'likes#destroy'
  resources :likes

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :stories, concerns: :commentable
  resources :notices, concerns: :commentable
  resources :suggestions, concerns: :commentable
  resources :snapshots, concerns: :commentable
  resources :kommentables, concerns: :commentable
  resources :comments, only: :index

  post '/tinymce_assets', to: 'tinymce_assets#create'

  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  namespace :admin do
    root to: 'users#index'
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
end

app/views/dreams/_header.html.haml
.header.dream-wrap
  %h2 사전 자료집
  %p.hidden-mobile.keep-all
    “100년 전, 일제의 총칼에도 굴하지 않고 독립만세를 외친 이들이 꿈꾸었던 세상은 어떤 것이었을까요?
    = succeed "제국(帝國)에서 민국(民國)으로의 전환을 선언한 임시정부가 그려보았던 해방된 나라는 어떤 곳이었을까요?" do
      %br/
    %br/
    %span 우리가 계승해야할 독립운동의 핵심 가치가 무엇인지 토론해 봅시다."
  %p.visible-mobile-block.keep-all
    “우리가 계승해야할 독립운동의 핵심 가치가 무엇인지 토론해 봅시다"

app/views/dreams/data.html.haml
= render 'dreams/header'
.notice-view
  .tab.js-menu-header
    / 하위메뉴 열림 "selected" class 추가
    %button.js-menu-toggle{type: "button"} 지역별 자료집
    %ul
      / %li
      /   = link_to '공통 자료집', dreams_value_path
      %li.selected
        = link_to '지역별 자료집', dreams_data_path
      %li
        = link_to '영상자료', dreams_interview_path
  .c-inner
    %h3 지역별 자료집
    %p 100년 토론광장의 지역별 자료집 입니다
    .list-data
      %ul
        %li
          .a-data.js-link.cursor-pointer{ 'data-url': "/100년토론광장자료집_수도.pdf", 'data-link-target': '_blank', style: "background-image:url(#{asset_url('data_ks.jpg')})" }
          %a{href: "/100년토론광장자료집_수도.pdf", target: '_blank'} 보기
        %li
          .a-data.js-link.cursor-pointer{ 'data-url': "/100년토론광장자료집_강원.pdf", 'data-link-target': '_blank', style: "background-image:url(#{asset_url('data_fu.jpg')})" }
          %a{href: "/100년토론광장자료집_강원.pdf", target: '_blank'} 보기
        %li
          .a-data.js-link.cursor-pointer{ 'data-url': "/100년토론광장자료집_호남제주.pdf", 'data-link-target': '_blank', style: "background-image:url(#{asset_url('data_hj.jpg')})" }
          %a{href: "/100년토론광장자료집_호남제주.pdf", target: '_blank'} 보기
        %li
          .a-data.js-link.cursor-pointer{ 'data-url': "/100년토론광장자료집_충청.pdf", 'data-link-target': '_blank', style: "background-image:url(#{asset_url('data_ch.jpg')})" }
          %a{href: "/100년토론광장자료집_충청.pdf", target: '_blank'} 보기
        %li
          .a-data.js-link.cursor-pointer{ 'data-url': "/100년토론광장자료집_영남.pdf", 'data-link-target': '_blank', style: "background-image:url(#{asset_url('data_bt.jpg')})" }
          %a{href: "/100년토론광장자료집_영남.pdf", target: '_blank'} 보기
    - comments_desc = capture do
      .com-desc
        %p 3.1운동 핵심 가치에 대한 여러분의 생각과 의견을 공유해주세요.
    = render 'comments/panel', commentable: Kommentable.data, desc: comments_desc

app/views/dreams/interview.html.haml
= render 'dreams/header'
.notice-view
  .tab.js-menu-header
    / 하위메뉴 열림 "selected" class 추가
    %button.js-menu-toggle{type: "button"} 영상자료
    %ul
      / %li
      /   = link_to '공통 자료집', dreams_value_path
      %li
        = link_to '지역별 자료집', dreams_data_path
      %li.selected
        = link_to '영상자료', dreams_interview_path
  .c-inner
    %h3 영상자료
    .list-video
      %ul
        - video_urls = %w(https://www.youtube.com/embed/rNMaCvqWHCQ https://www.youtube.com/embed/rOyGNcr0s5k https://www.youtube.com/embed/t00aDEjPuNk)
        - video_urls.each do |video_url|
          - video = VideoInfo.new(video_url)
          %li
            .video.js-dimd-open.cursor-pointer{ 'data-dimd-open-url': video_url, style: "background-image: url(#{video.thumbnail_large});" }
              %button{ type: "button" }
                %span 동영상 열기
      / [02.18] 딤드레이어 추가
      .dimd-wrap.js-dimd-wrap
        .dimd-inner
          .video-layer
            %iframe{ frameborder: "0", allowfullscreen: true }
          %button.js-dimd-close{:type => "button"}
            %span 동영상 레이어 닫기
      / //[02.18] 딤드레이어 추가

      .btn
        %a{href: "https://www.together100.go.kr/lay2/bbs/S1T11C23/G/6/list.do?cat=5", target: '_blank'} 더 보기


    - comments_desc = capture do
      .com-desc
        %p 3.1운동 핵심 가치에 대한 여러분의 생각과 의견을 공유해주세요.
    = render 'comments/panel', commentable: Kommentable.interview, desc: comments_desc

app/views/dreams/value.html.haml
= render 'dreams/header'
.notice-view
  .tab.js-menu-header
    / 하위메뉴 열림 "selected" class 추가
    %button.js-menu-toggle{type: "button"} 공통 자료집
    %ul
      / %li.selected
      /   = link_to '공통 자료집', dreams_value_path
      %li
        = link_to '지역별 자료집', dreams_data_path
      %li
        = link_to '영상자료', dreams_interview_path
  .c-inner
    %h3 100년 토론광장 공통 자료집
    %p
      민국 100년! 선열이 꿈꾼 나라,
      = succeed "우리가 만들 세상" do
        %br/
    .video-wrap
      / .video #video
      .btn
        / %a.go-view{href: "#"} 바로보기
        %a.download{ href: "void(0);", onclick: "alert('준비 중입니다.');return false;" } 다운로드
    - comments_desc = capture do
      .com-desc
        %p 3.1운동 핵심 가치에 대한 여러분의 생각과 의견을 공유해주세요.
    = render 'comments/panel', commentable: Kommentable.value, desc: comments_desc