config/routes.rb
Rails.application.routes.draw do
  mount AcmePlugin::Engine, at: '/'

  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  root 'pages#home'
  get :faq, to: 'pages#faq'

  get :about, to: 'pages#about'
  get :caution, to: 'pages#caution'
  get :map, to: 'pages#map'
  get :schedule, to: 'pages#schedule'
  get :application, to: 'pages#application'
  get 'sites/:area_code', to: 'pages#site', as: :site

  get :group, to: 'pages#group'

  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'

  get 'dreams/value', to: 'dreams#value'
  get 'dreams/interview', to: 'dreams#interview'
  get 'dreams/data', to: 'dreams#data'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'

  delete :likes, to: 'likes#destroy'
  resources :likes

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :stories, concerns: :commentable
  resources :notices, concerns: :commentable
  resources :suggestions, concerns: :commentable
  resources :snapshots, concerns: :commentable
  resources :kommentables, concerns: :commentable
  resources :comments, only: :index

  post '/tinymce_assets', to: 'tinymce_assets#create'

  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  namespace :admin do
    root to: 'users#index'
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  include Likable

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  scope :order_recent, -> { order(created_at: :desc) }
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @notices = Notice.order_recent.page(params[:page]).per(6)
  end

  def show
    @notice = Notice.find(params[:id])
    @notice.reads_count += 1
    @notice.save
  end

  def new
    authorize Notice.new
  end

  def create
    @notice = Notice.new notice_params
    authorize @notice

    @notice.user = current_user
    if @notice.save
      flash[:success] = '게시되었습니다'
      redirect_to @notice
    else
      errors_to_flash(@notice)
      render :new
    end
  end

  def edit
    @notice = Notice.find(params[:id])
    authorize @notice
  end

  def update
    @notice = Notice.find(params[:id])
    authorize @notice

    @notice.assign_attributes(notice_params)
    if @notice.save
      flash[:success] = '저장되었습니다'
      redirect_to @notice
    else
      errors_to_flash(@notice)
      render :new
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    authorize @notice

    if @notice.destroy
      flash[:success] = '삭제되었습니다'
      redirect_to notices_path
    else
      errors_to_flash(@notice)
      redirect_to @notice
    end
  end

  private

  def notice_params
    params.require(:notice).permit(:title, :body)
  end
end

app/views/notices/_form.html.haml
- notice ||= (@notice || Notice.new)
= form_with model: notice do |f|
  .write-box
    %ul
      %li
        = f.label :title, '제목'
        = f.text_field :title
      %li
        = f.label :body, '내용'
        = f.text_area :body, class: 'tinymce js-tinymce', 'data-content-css': asset_url('tinymce_content.css')
  .def-btn
    %a{href: notices_path} 취소
    = f.submit (f.object.persisted? ? "수정" : "등록"), class: 'active'

app/views/notices/_notice.html.haml
%li
  = link_to notice.title, notice_path(notice, page: params[:page])
  .info
    %span.date
      %i> 날짜
      = static_day_f(notice.created_at)
    %span.view
      %i> 조회
      = notice.reads_count

app/views/notices/_template.html.haml
.header.notice
  %h2 소식과 공지
  %p.keep-all
    “100년 토론광장의 새 소식과 공지사항을 알려드립니다.”
.notice-view
  .tab.js-menu-header
    / 하위메뉴 열림 "selected" class 추가
    %button.js-menu-toggle{type: "button"} 공지
    %ul
      %li
        %a{href: stories_path} 소식
      %li.selected
        %a{href: notices_path} 공지
      %li
        %a{href: faq_path} FAQ
  .c-inner
    %h3 공지 사항
    %p
      100년 토론광장의 공지사항을
      = succeed "알려드립니다" do
        %br/
    = content

app/views/notices/edit.html.haml
- content = capture do
  = render 'notices/form', notice: @notice
= render 'notices/template', content: content

app/views/notices/index.html.haml
- content = capture do
  .list-box
    %ul.notice-list
      = render @notices
    = paginate @notices
    - if policy(Notice).new?
      %a.btn-write{href: new_notice_path} 글쓰기
= render 'notices/template', content: content

app/views/notices/new.html.haml
.header.notice
  %h2 소식과 공지
  %p
    “100년 전, 선조들이 꿈꾸었던 나라를 현실로 만들려면, 지금 우리는 무엇을 해야 할까요?
    = succeed "어떤 문제를 어떻게 해결해야 할까요?”" do
      %br/
.notice-view
  .tab
    / 하위메뉴 열림 "selected" class 추가
    %button{type: "button"} 공지
    %ul
      %li
        %a{href: stories_path} 소식
      %li.selected
        %a{href: notices_path} 공지
      %li
        %a{href: faq_path} FAQ
  .c-inner
    %h3 공지 사항
    %p
      100년 토론광장의 공지사항을
      = succeed "알려드립니다" do
        %br/
    .write-box
      %ul
        %li
          %label{for: "subject"} 제목
          %input#subject{type: "text"}/
          %p.err 제목을 입력해주세요.
        %li
          %label{for: "conts"} 내용
          %textarea#conts
          %p.err 내용을 입력해주세요.
        %li
          %em 썸네일
          .file-wrap
            %input#thumbFile{type: "file"}/
            %label{for: "thumbFile"} 파일첨부
            %input{title: "첨부파일명", type: "text"}/
          %p 권장 사이즈 000 X 000
    .def-btn
      %a{href: notices_path} 목록
      %a.active{href: "#"} 수정

app/views/notices/show.html.haml
- content = capture do
  .viewbox
    %h4= @notice.title
    .info
      %span.date
        %i> 날짜
        = static_day_f(@notice.created_at)
      %span.view
        %i> 조회
        = @notice.reads_count
    .cnts.cnts-img.js-fit-vids
      %p!= @notice.body
    .sns-wrap
      = render 'likes/button', likable: @notice

      %a.facebook{href: "https://www.facebook.com/sharer/sharer.php?u=#{polymorphic_url(@notice)}", target: '_blank', title: '공유하기'} 공유하기
      .btn.copy-url.cursor-pointer.js-clipboard{'data-clipboard-text': polymorphic_url(@notice)} 주소복사
  .b-btn
    %a.list{href: notices_path(page: params[:page])} 목록
    - if policy(@notice).edit?
      = link_to '수정', [:edit, @notice], class: 'modify'
    - if policy(@notice).destroy?
      = link_to '삭제', @notice, method: :delete, class: 'delete', 'data-confirm': '정말 삭제하시겠습니까?'
  = render 'comments/panel', commentable: @notice

= render 'notices/template', content: content