config/routes.rb
Rails.application.routes.draw do
  mount AcmePlugin::Engine, at: '/'

  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  root 'pages#home'
  get :faq, to: 'pages#faq'

  get :about, to: 'pages#about'
  get :caution, to: 'pages#caution'
  get :map, to: 'pages#map'
  get :schedule, to: 'pages#schedule'
  get :application, to: 'pages#application'
  get 'sites/:area_code', to: 'pages#site', as: :site

  get :group, to: 'pages#group'

  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'

  get 'dreams/value', to: 'dreams#value'
  get 'dreams/interview', to: 'dreams#interview'
  get 'dreams/data', to: 'dreams#data'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'

  delete :likes, to: 'likes#destroy'
  resources :likes

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :stories, concerns: :commentable
  resources :notices, concerns: :commentable
  resources :suggestions, concerns: :commentable
  resources :snapshots, concerns: :commentable
  resources :kommentables, concerns: :commentable
  resources :comments, only: :index

  post '/tinymce_assets', to: 'tinymce_assets#create'

  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  namespace :admin do
    root to: 'users#index'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likable
  paginates_per 20

  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true

  scope :order_recent, -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    load_commentable

    @comments = @commentable.comments.order_recent.page(params[:page])
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    load_commentable

    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment
    if @comment.save
      redirect_to commentable_url(@commentable), notice: '댓글이 게시되었습니다.'
    else
      errors_to_flash(@comment)
      session[:error_comment_body] = @comment.body
      redirect_to commentable_url(@commentable)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def update
    @comment = Comment.find(params[:id])
    authorize @comment

    @comment.assign_attributes(comment_params)
    if @comment.save
      flash[:success] = '저장되었습니다'
    else
      errors_to_flash(@story)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment

    if @comment.destroy
      flash[:success] = '삭제되었습니다'
    else
      errors_to_flash(@comment)
    end

    @commentable = @comment.commentable
    @comments = @commentable.comments.order_recent.page(params[:page])
  end

  private

  def commentable_url commentable
    case commentable.try(:path_slug)
    when "kommentables_interview"
      dreams_interview_path
    when "kommentables_data"
      dreams_data_path
    # when "kommentables_value"
    # dreams_value_path
    else
      polymorphic_url(commentable)
    end
  end

  def load_commentable
    if params[:commentable_type].present? and params[:commentable_id].present?
      resource = params[:commentable_type].safe_constantize
      if resource.present?
        @commentable = resource.find(params[:commentable_id])
      end
    else
      resource, id = request.path.split('/')[1,2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_body.html.haml
= simple_format comment.body

app/views/comments/_comment.html.haml
- comment_dom_id = "rnd-#{SecureRandom.uuid}"
%li{ id: comment_dom_id }
  .info
    %span.writer
      %i> 작성자
      = comment.user.name
    %span.date
      %i> 날짜
      = static_day_f comment.created_at
    - counter_dom_id = "rnd-#{SecureRandom.uuid}"
    = render 'likes/counter', likable: comment, dom_id: counter_dom_id
  - if local_assigns[:show_form]
    = render 'comments/form', comment: comment, class_name: 'write-box', dom_id: comment_dom_id, list_dom_id: list_dom_id
  - else
    = render 'comments/body', comment: comment

  - unless local_assigns[:show_form]
    .btn
      - if policy(comment).edit?
        = link_to '수정', edit_comment_path(comment, dom_id: comment_dom_id, list_dom_id: list_dom_id), remote: true, class: 'link-btn modify'
      - if policy(comment).destroy?
        = link_to '삭제', comment_path(comment, list_dom_id: list_dom_id, page: params[:page]), method: :delete, remote: true, 'data-confirm': '정말 삭제하시겠습니까?', class: 'link-btn delete'
      - if policy(comment).like? or !user_signed_in?
        = render 'likes/button', likable: comment, class_name: 'recomd', counter_dom_id: counter_dom_id

app/views/comments/_form.html.haml
- commentable = local_assigns[:commentable] || comment.commentable
= form_with model: (comment.persisted? ? comment : [commentable, comment]), local: !comment.persisted?, id: local_assigns[:dom_id], class: local_assigns[:class_name] do |f|
  = hidden_field_tag :dom_id, local_assigns[:dom_id]
  = hidden_field_tag :list_dom_id, list_dom_id
  = f.text_area :body, value: session[:error_comment_body] || comment.body, title: "댓글입력"
  - session[:error_comment_body] = nil

  = f.submit '등록'
  - if comment.persisted?
    = link_to '취소', comment_path(comment, dom_id: local_assigns[:dom_id], list_dom_id: list_dom_id), remote: true, class: 'link-btn', style: '    top: 50px; background: white; color: #006ebc; border: 2px solid;'

app/views/comments/_list.html.haml
%div{ id: dom_id }
  .cmt-list
    %ul
      - comments.each do |comment|
        = render 'comments/comment', comment: comment, list_dom_id: dom_id
  = paginate comments, params: { controller: 'comments', action: 'index', commentable_type: commentable.class.to_s, commentable_id: commentable.id, dom_id: dom_id }, remote: true

app/views/comments/_panel.html.haml
.comment-wrap
  = local_assigns[:desc]
  - comment_list_dom_id = "rnd-#{SecureRandom.uuid}"
  = render 'comments/form', commentable: commentable, comment: Comment.new, class_name: 'cmt-write', list_dom_id: comment_list_dom_id
  - if commentable.comments_count > 0
    - comments = commentable.comments.order_recent.page(1)
    = render 'comments/list', commentable: commentable, comments: comments, dom_id: comment_list_dom_id

app/views/comments/destroy.js.erb
$('#<%= params['list_dom_id'] %>').replaceWith('<%= j(render 'comments/list', commentable: @commentable, comments: @comments, dom_id: params['list_dom_id']) %>');

app/views/comments/edit.js.erb
$('#<%= params[:dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, list_dom_id: params[:list_dom_id], show_form: true) %>');

app/views/comments/index.js.erb
$('#<%= params['dom_id'] %>').replaceWith('<%= j(render 'comments/list', commentable: @commentable, comments: @comments, dom_id: params['dom_id']) %>');
$.scrollTo($('#<%= params['dom_id'] %>'), { offset: { top: -100 } });

app/views/comments/show.js.erb
$('#<%= params['dom_id'] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, dom_id: params['dom_id'], list_dom_id: params[:list_dom_id]) %>');

app/views/comments/update.js.erb
$('#<%= params[:dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, list_dom_id: params[:list_dom_id]) %>');