config/routes.rb
Rails.application.routes.draw do
  mount AcmePlugin::Engine, at: '/'

  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  root 'pages#home'
  get :faq, to: 'pages#faq'

  get :about, to: 'pages#about'
  get :caution, to: 'pages#caution'
  get :map, to: 'pages#map'
  get :schedule, to: 'pages#schedule'
  get :application, to: 'pages#application'
  get 'sites/:area_code', to: 'pages#site', as: :site

  get :group, to: 'pages#group'

  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'

  get 'dreams/value', to: 'dreams#value'
  get 'dreams/interview', to: 'dreams#interview'
  get 'dreams/data', to: 'dreams#data'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'

  delete :likes, to: 'likes#destroy'
  resources :likes

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :stories, concerns: :commentable
  resources :notices, concerns: :commentable
  resources :suggestions, concerns: :commentable
  resources :snapshots, concerns: :commentable
  resources :kommentables, concerns: :commentable
  resources :comments, only: :index

  post '/tinymce_assets', to: 'tinymce_assets#create'

  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  namespace :admin do
    root to: 'users#index'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likable, polymorphic: true, counter_cache: true
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    render_404 and return unless user_signed_in?

    @likable = params[:likable_type].try(:safe_constantize).try(:find, params[:likable_id])
    render_404 and return if @likable.blank?

    @likable.likes.create(user: current_user)

    respond_to do |format|
      format.html { redirect_to @likable }
      format.js
    end
  end

  def destroy
    render_404 and return unless user_signed_in?

    @likable = params[:likable_type].try(:safe_constantize).try(:find, params[:likable_id])
    render_404 and return if @likable.blank?

    @likable.likes.find_by(user: current_user).try(:destroy)

    respond_to do |format|
      format.html { redirect_to @likable }
      format.js
    end
  end
end

app/views/likes/_button.html.haml
- like_btn_label = case likable
- when Comment
  - '추천'
- else
  - '공감해요'
- if likable.likes_count > 0 and !likable.is_a?(Comment)
  - like_btn_label = likable.likes_count

- button_dom_id = "rnd-#{SecureRandom.uuid}"
- like_btn_path = likes_path(likable_type: likable.class.to_s, likable_id: likable.id, dom_id: button_dom_id, class_name: local_assigns[:class_name], counter_dom_id: local_assigns[:counter_dom_id])

- if policy(likable).like? or !user_signed_in?
  %span{ id: button_dom_id }
    - if user_signed_in?
      - if likable.like_by?(current_user)
        = link_to like_btn_label, like_btn_path, method: :delete, remote: true, class: "like active link-btn #{local_assigns[:class_name]}"
      - else
        = link_to like_btn_label, like_btn_path, method: :post, remote: true, class: "like link-btn #{local_assigns[:class_name]}"
    - else
      = link_to like_btn_label, new_user_session_path, class: "like link-btn #{local_assigns[:class_name]}"

app/views/likes/_counter.html.haml
%span.like{ id: local_assigns[:dom_id] }
  %i> 좋아요
  = likable.likes_count

app/views/likes/create.js.erb
$('#<%= params[:dom_id] %>').replaceWith('<%= j(render 'likes/button', likable: @likable, class_name: params[:class_name], counter_dom_id: params[:counter_dom_id]) %>');
<% if params[:counter_dom_id].present? %>
  $('#<%= params[:counter_dom_id] %>').replaceWith('<%= j(render 'likes/counter', likable: @likable, dom_id: params[:counter_dom_id]) %>');
<% end %>

app/views/likes/destroy.js.erb
$('#<%= params[:dom_id] %>').replaceWith('<%= j(render 'likes/button', likable: @likable, class_name: params[:class_name], counter_dom_id: params[:counter_dom_id]) %>');
<% if params[:counter_dom_id].present? %>
  $('#<%= params[:counter_dom_id] %>').replaceWith('<%= j(render 'likes/counter', likable: @likable, dom_id: params[:counter_dom_id]) %>');
<% end %>